[package]
name = "chrono-gateway"
version.workspace = true
edition.workspace = true
license.workspace = true


[dependencies]
chrono-ipc = { workspace = true }
chrono-config = { workspace = true }
chrono-api = { workspace = true }
chrono-adapter-telegram = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
futures = { workspace = true }
uuid = { workspace = true }
